# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Amharic Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - categories-rdf
  - medium
  - s3
  - securepollglobal
  - wikidataclient
  - growthexperiments
