# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wiktionary Zazaki.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
    - wiktionary
    - s5
    - commonsuploads
    - wikidataclient
    - small
