# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the English Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - flaggedrevs
  - flow-labs
  - flow_only_labs
  - large
  - mobile-anon-talk # T293946
  - pageassessments
  - s1
  - securepollglobal
  - wikidataclient
  - growthexperiments

wmgSiteLogo1x: '/static/images/project-logos/enwiki.png'
