# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Turkish Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - categories-rdf
  - cirrussearch-big-indices
  - flaggedrevs
  - growthexperiments
  - large
  - s2
  - securepollglobal
  - wikidataclient
